# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main
- develop

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: windows-latest

stages:
- stage: CI
  jobs:
  - job: CIBuild

    steps:
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'
    - task: gitversion/execute@0
      inputs:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'
        updateAssemblyInfo: true
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Martins Sonar Cloud'
        organization: 'nkdagility'
        scannerMode: 'MSBuild'
        projectKey: 'azure-devops-export-for-actionable-agile:main'
        projectName: 'azure-devops-export-for-actionable-agile'
        projectVersion: '$(GITVERSION.SemVer)' 

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: 

    - task: SonarCloudAnalyze@1
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
      enabled: false

    - task: PublishSymbols@2
      inputs:
        SearchPattern: '**/bin/**/*.pdb'
        SymbolServerType: 'TeamServices'
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
      enabled: false

    - task: zip@0
      inputs:
        pathToZipFolder: '$(Build.SourcesDirectory)\src\AzureDevOps.Export.ActionableAgile.ConsoleUI\bin\Debug\net8.0\'
        pathToZipFile: '$(Build.ArtifactStagingDirectory)/AzureDevOps.Export.ActionableAgile-v$(GITVERSION.SemVer).zip'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Release
  jobs:
  - job: GitHubRelease
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)'
        Contents: '\drop\AzureDevOps.Export.ActionableAgile*.zip'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'GitHub connection 4'
        repositoryName: 'nkdAgility/azure-devops-export-for-actionable-agile'
        action: 'create'
        target: '$(Build.BuildNumber)'
        tagSource: 'gitTag'
        title: 'v$(Build.BuildNumber) - $(BUILD_SOURCEVERSIONMESSAGE)'
        releaseNotesSource: 'inline'
        releaseNotesInline: |
          $(prbody)
          
          $(BUILD_SOURCEVERSIONMESSAGE) for $(BUILD_SOURCEVERSIONAUTHOR)
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'issueBased'
